name: Verify

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # checkout sources

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U apio
          sudo apt install -y gtkwave

      - name: Install Apio packages
        run: apio install -a

      - name: Verify Apio code
        run: apio verify

      - name: Simulate Apio code
        run: apio sim
