name: Verify

on:
  push:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # checkout sources

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U apio
          sudo apt install -y gtkwave

      - name: Install Apio packages
        run: apio install -a

  test:
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
      - name: Run test file
        run: |
          chmod +x test.sh
          ./test.sh
